### ISSUE TITLE
SSL Doesn't work

### ISSUE THREAD

**Issue by theqwertman** [bobobo1618/docpad-plugin-sunny#19]
Any attempt to connect with the SSL option set to true results in `Hostname/IP doesn't match certificate's altnames`

**Comment by bobobo1618** [comment]
This plugin is a wrapper around [Sunny](https://github.com/ryan-roemer/node-sunny) and it seems like this issue would be from there.

If you can show me an example of Sunny working with a config that breaks this plugin, I'll accept it, otherwise you'll have more luck filing an issue against Sunny directly.
